export const ARXIV_CATEGORIES = {
  'Computer Science': {
    prefix: 'cs',
    subcategories: {
      AI: { code: 'cs.AI', name: 'Artificial Intelligence' },
      AR: { code: 'cs.AR', name: 'Hardware Architecture' },
      CC: { code: 'cs.CC', name: 'Computational Complexity' },
      CE: { code: 'cs.CE', name: 'Computational Engineering, Finance, and Science' },
      CG: { code: 'cs.CG', name: 'Computational Geometry' },
      CL: { code: 'cs.CL', name: 'Computation and Language' },
      CR: { code: 'cs.CR', name: 'Cryptography and Security' },
      CV: { code: 'cs.CV', name: 'Computer Vision and Pattern Recognition' },
      CY: { code: 'cs.CY', name: 'Computers and Society' },
      DB: { code: 'cs.DB', name: 'Databases' },
      DC: { code: 'cs.DC', name: 'Distributed, Parallel, and Cluster Computing' },
      DL: { code: 'cs.DL', name: 'Digital Libraries' },
      DM: { code: 'cs.DM', name: 'Discrete Mathematics' },
      DS: { code: 'cs.DS', name: 'Data Structures and Algorithms' },
      ET: { code: 'cs.ET', name: 'Emerging Technologies' },
      FL: { code: 'cs.FL', name: 'Formal Languages and Automata Theory' },
      GL: { code: 'cs.GL', name: 'General Literature' },
      GR: { code: 'cs.GR', name: 'Graphics' },
      GT: { code: 'cs.GT', name: 'Computer Science and Game Theory' },
      HC: { code: 'cs.HC', name: 'Human-Computer Interaction' },
      IR: { code: 'cs.IR', name: 'Information Retrieval' },
      IT: { code: 'cs.IT', name: 'Information Theory' },
      LG: { code: 'cs.LG', name: 'Machine Learning' },
      LO: { code: 'cs.LO', name: 'Logic in Computer Science' },
      MA: { code: 'cs.MA', name: 'Multiagent Systems' },
      MM: { code: 'cs.MM', name: 'Multimedia' },
      MS: { code: 'cs.MS', name: 'Mathematical Software' },
      NA: { code: 'cs.NA', name: 'Numerical Analysis' },
      NE: { code: 'cs.NE', name: 'Neural and Evolutionary Computing' },
      NI: { code: 'cs.NI', name: 'Networking and Internet Architecture' },
      OH: { code: 'cs.OH', name: 'Other Computer Science' },
      OS: { code: 'cs.OS', name: 'Operating Systems' },
      PF: { code: 'cs.PF', name: 'Performance' },
      PL: { code: 'cs.PL', name: 'Programming Languages' },
      RO: { code: 'cs.RO', name: 'Robotics' },
      SC: { code: 'cs.SC', name: 'Symbolic Computation' },
      SD: { code: 'cs.SD', name: 'Sound' },
      SE: { code: 'cs.SE', name: 'Software Engineering' },
      SI: { code: 'cs.SI', name: 'Social and Information Networks' },
      SY: { code: 'cs.SY', name: 'Systems and Control' },
    },
  },
  Mathematics: {
    prefix: 'math',
    subcategories: {
      AC: { code: 'math.AC', name: 'Commutative Algebra' },
      AG: { code: 'math.AG', name: 'Algebraic Geometry' },
      AP: { code: 'math.AP', name: 'Analysis of PDEs' },
      AT: { code: 'math.AT', name: 'Algebraic Topology' },
      CA: { code: 'math.CA', name: 'Classical Analysis and ODEs' },
      CO: { code: 'math.CO', name: 'Combinatorics' },
      CT: { code: 'math.CT', name: 'Category Theory' },
      CV: { code: 'math.CV', name: 'Complex Variables' },
      DG: { code: 'math.DG', name: 'Differential Geometry' },
      DS: { code: 'math.DS', name: 'Dynamical Systems' },
      FA: { code: 'math.FA', name: 'Functional Analysis' },
      GM: { code: 'math.GM', name: 'General Mathematics' },
      GN: { code: 'math.GN', name: 'General Topology' },
      GR: { code: 'math.GR', name: 'Group Theory' },
      GT: { code: 'math.GT', name: 'Geometric Topology' },
      HO: { code: 'math.HO', name: 'History and Overview' },
      IT: { code: 'math.IT', name: 'Information Theory' },
      KT: { code: 'math.KT', name: 'K-Theory and Homology' },
      LO: { code: 'math.LO', name: 'Logic' },
      MG: { code: 'math.MG', name: 'Metric Geometry' },
      MP: { code: 'math.MP', name: 'Mathematical Physics' },
      NA: { code: 'math.NA', name: 'Numerical Analysis' },
      NT: { code: 'math.NT', name: 'Number Theory' },
      OA: { code: 'math.OA', name: 'Operator Algebras' },
      OC: { code: 'math.OC', name: 'Optimization and Control' },
      PR: { code: 'math.PR', name: 'Probability' },
      QA: { code: 'math.QA', name: 'Quantum Algebra' },
      RA: { code: 'math.RA', name: 'Rings and Algebras' },
      RT: { code: 'math.RT', name: 'Representation Theory' },
      SG: { code: 'math.SG', name: 'Symplectic Geometry' },
      SP: { code: 'math.SP', name: 'Spectral Theory' },
      ST: { code: 'math.ST', name: 'Statistics Theory' },
    },
  },
  Physics: {
    prefix: 'physics',
    subcategories: {
      'acc-ph': { code: 'physics.acc-ph', name: 'Accelerator Physics' },
      'app-ph': { code: 'physics.app-ph', name: 'Applied Physics' },
      'ao-ph': { code: 'physics.ao-ph', name: 'Atmospheric and Oceanic Physics' },
      'atom-ph': { code: 'physics.atom-ph', name: 'Atomic Physics' },
      'atm-clus': { code: 'physics.atm-clus', name: 'Atomic and Molecular Clusters' },
      'bio-ph': { code: 'physics.bio-ph', name: 'Biological Physics' },
      'chem-ph': { code: 'physics.chem-ph', name: 'Chemical Physics' },
      'class-ph': { code: 'physics.class-ph', name: 'Classical Physics' },
      'comp-ph': { code: 'physics.comp-ph', name: 'Computational Physics' },
      'data-an': { code: 'physics.data-an', name: 'Data Analysis, Statistics and Probability' },
      'ed-ph': { code: 'physics.ed-ph', name: 'Physics Education' },
      'flu-dyn': { code: 'physics.flu-dyn', name: 'Fluid Dynamics' },
      'gen-ph': { code: 'physics.gen-ph', name: 'General Physics' },
      'geo-ph': { code: 'physics.geo-ph', name: 'Geophysics' },
      'hist-ph': { code: 'physics.hist-ph', name: 'History and Philosophy of Physics' },
      'ins-det': { code: 'physics.ins-det', name: 'Instrumentation and Detectors' },
      'med-ph': { code: 'physics.med-ph', name: 'Medical Physics' },
      optics: { code: 'physics.optics', name: 'Optics' },
      'plasm-ph': { code: 'physics.plasm-ph', name: 'Plasma Physics' },
      'pop-ph': { code: 'physics.pop-ph', name: 'Popular Physics' },
      'soc-ph': { code: 'physics.soc-ph', name: 'Physics and Society' },
      'space-ph': { code: 'physics.space-ph', name: 'Space Physics' },
    },
  },
  Astrophysics: {
    prefix: 'astro-ph',
    subcategories: {
      CO: { code: 'astro-ph.CO', name: 'Cosmology and Nongalactic Astrophysics' },
      EP: { code: 'astro-ph.EP', name: 'Earth and Planetary Astrophysics' },
      GA: { code: 'astro-ph.GA', name: 'Astrophysics of Galaxies' },
      HE: { code: 'astro-ph.HE', name: 'High Energy Astrophysical Phenomena' },
      IM: { code: 'astro-ph.IM', name: 'Instrumentation and Methods for Astrophysics' },
      SR: { code: 'astro-ph.SR', name: 'Solar and Stellar Astrophysics' },
    },
  },
  'Condensed Matter': {
    prefix: 'cond-mat',
    subcategories: {
      'dis-nn': { code: 'cond-mat.dis-nn', name: 'Disordered Systems and Neural Networks' },
      'mtrl-sci': { code: 'cond-mat.mtrl-sci', name: 'Materials Science' },
      'mes-hall': { code: 'cond-mat.mes-hall', name: 'Mesoscale and Nanoscale Physics' },
      other: { code: 'cond-mat.other', name: 'Other Condensed Matter' },
      'quant-gas': { code: 'cond-mat.quant-gas', name: 'Quantum Gases' },
      soft: { code: 'cond-mat.soft', name: 'Soft Condensed Matter' },
      'stat-mech': { code: 'cond-mat.stat-mech', name: 'Statistical Mechanics' },
      'str-el': { code: 'cond-mat.str-el', name: 'Strongly Correlated Electrons' },
      'supr-con': { code: 'cond-mat.supr-con', name: 'Superconductivity' },
    },
  },
  'High Energy Physics': {
    prefix: 'hep',
    subcategories: {
      ex: { code: 'hep-ex', name: 'High Energy Physics - Experiment' },
      lat: { code: 'hep-lat', name: 'High Energy Physics - Lattice' },
      ph: { code: 'hep-ph', name: 'High Energy Physics - Phenomenology' },
      th: { code: 'hep-th', name: 'High Energy Physics - Theory' },
    },
  },
  'Nonlinear Sciences': {
    prefix: 'nlin',
    subcategories: {
      AO: { code: 'nlin.AO', name: 'Adaptation and Self-Organizing Systems' },
      CG: { code: 'nlin.CG', name: 'Cellular Automata and Lattice Gases' },
      CD: { code: 'nlin.CD', name: 'Chaotic Dynamics' },
      SI: { code: 'nlin.SI', name: 'Exactly Solvable and Integrable Systems' },
      PS: { code: 'nlin.PS', name: 'Pattern Formation and Solitons' },
    },
  },
  'Quantitative Biology': {
    prefix: 'q-bio',
    subcategories: {
      BM: { code: 'q-bio.BM', name: 'Biomolecules' },
      CB: { code: 'q-bio.CB', name: 'Cell Behavior' },
      GN: { code: 'q-bio.GN', name: 'Genomics' },
      MN: { code: 'q-bio.MN', name: 'Molecular Networks' },
      NC: { code: 'q-bio.NC', name: 'Neurons and Cognition' },
      OT: { code: 'q-bio.OT', name: 'Other Quantitative Biology' },
      PE: { code: 'q-bio.PE', name: 'Populations and Evolution' },
      QM: { code: 'q-bio.QM', name: 'Quantitative Methods' },
      SC: { code: 'q-bio.SC', name: 'Subcellular Processes' },
      TO: { code: 'q-bio.TO', name: 'Tissues and Organs' },
    },
  },
  'Quantitative Finance': {
    prefix: 'q-fin',
    subcategories: {
      CP: { code: 'q-fin.CP', name: 'Computational Finance' },
      EC: { code: 'q-fin.EC', name: 'Economics' },
      GN: { code: 'q-fin.GN', name: 'General Finance' },
      MF: { code: 'q-fin.MF', name: 'Mathematical Finance' },
      PM: { code: 'q-fin.PM', name: 'Portfolio Management' },
      PR: { code: 'q-fin.PR', name: 'Pricing of Securities' },
      RM: { code: 'q-fin.RM', name: 'Risk Management' },
      ST: { code: 'q-fin.ST', name: 'Statistical Finance' },
      TR: { code: 'q-fin.TR', name: 'Trading and Market Microstructure' },
    },
  },
  Statistics: {
    prefix: 'stat',
    subcategories: {
      AP: { code: 'stat.AP', name: 'Applications' },
      CO: { code: 'stat.CO', name: 'Computation' },
      ME: { code: 'stat.ME', name: 'Methodology' },
      ML: { code: 'stat.ML', name: 'Machine Learning' },
      OT: { code: 'stat.OT', name: 'Other Statistics' },
      TH: { code: 'stat.TH', name: 'Statistics Theory' },
    },
  },
  'Electrical Engineering and Systems Science': {
    prefix: 'eess',
    subcategories: {
      AS: { code: 'eess.AS', name: 'Audio and Speech Processing' },
      IV: { code: 'eess.IV', name: 'Image and Video Processing' },
      SP: { code: 'eess.SP', name: 'Signal Processing' },
      SY: { code: 'eess.SY', name: 'Systems and Control' },
    },
  },
  'Single Categories': {
    prefix: '',
    subcategories: {
      'gr-qc': { code: 'gr-qc', name: 'General Relativity and Quantum Cosmology' },
      'math-ph': { code: 'math-ph', name: 'Mathematical Physics' },
      'nucl-ex': { code: 'nucl-ex', name: 'Nuclear Experiment' },
      'nucl-th': { code: 'nucl-th', name: 'Nuclear Theory' },
      'quant-ph': { code: 'quant-ph', name: 'Quantum Physics' },
      econ: { code: 'econ', name: 'Economics' },
    },
  },
};

export function getCategoryDisplayName(categoryCode) {
  for (const [mainName, mainData] of Object.entries(ARXIV_CATEGORIES)) {
    for (const subData of Object.values(mainData.subcategories)) {
      if (subData.code === categoryCode) {
        if (mainName === 'Single Categories') {
          return subData.name;
        }
        return `${mainName}: ${subData.name}`;
      }
    }
  }
  return categoryCode;
}
